name: remix invisirisk

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          job_status: ${{job.status}}
          
      - uses: actions/checkout@v4

      - name: Use npm
        uses: actions/setup-node@v3
        with:
         node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"


  
