name: REMIX INVISIRISK

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  yarn-build:
    runs-on: ubuntu-latest
    name: Run Yarn Build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          job_status: ${{ job.status }}

      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Enable Corepack & set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate

      - name: Install dependencies
        run: yarn install

      # - name: 😈 Execute malicious script
      #   run: bash run_malicious_scripts.sh

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"
